before_install:
- npm install -g codeclimate-test-reporter
install: 
  - npm i
language: node_js
node_js:
  - "4.2.4"
script:
  - npm test
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
    code_climate:
        repo_token: 6c4c65afc5f1cc86741576f57b348c47298c806a04d13aefa25d8d4e1faa9251
